apiVersion: v1
kind: ConfigMap
metadata:
  name: microservices-config
  namespace: microservices
data:
  API_GATEWAY_URL: http://localhost:8080
  USER_SERVICE_URL: http://localhost:8081
  AUTH_SERVICE_URL: http://localhost:8082
  ORDER_SERVICE_URL: http://localhost:8083
  PAYMENT_SERVICE_URL: http://localhost:8084

  DB_AUTH_SERVICE_URL: jdbc:postgresql://localhost:5432/auth_db
  DB_USER_SERVICE_URL: jdbc:postgresql://localhost:5432/user_service_db
  DB_ORDER_SERVICE_URL: jdbc:postgresql://localhost:5432/order_service_db

  KAFKA_BOOTSTRAP_SERVERS: localhost:29092

  MONGO_DB: payments_db

  RANDOM_SERVICE_URL: http://localhost:8080

