apiVersion: v1
kind: Service
metadata:
  name: postgres-auth-service
  namespace: microservices
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres-auth-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-auth-service
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-auth-service
  template:
    metadata:
      labels:
        app: postgres-auth-service
    spec:
      containers:
        - name: postgres-auth-service
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "auth_db"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: microservices-secret
                  key: DB_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: microservices-secret
                  key: DB_PASSWORD